name: Build and Test

on:
  push:
    branches: [main, feat/*, feature/*, docs/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. Install ONLY clang-format first (It's fast)
      - name: Install Clang-Format
        run: |
           sudo apt-get update
           sudo apt-get install -y clang-format

      # 2. Check Formatting (Replicates your PowerShell script)
      # We use 'find' to exclude 'vendor' folder, mimicking ignore file.
      - name: Check Code Formatting
        run: |
           echo "Verifying code style..."
           find src -type f \( -name "*.cpp" -o -name "*.h" \) | xargs clang-format -style=file --dry-run
             #--Werror removed for clang version 20.1.8 from VS 2026 is yet to be supported for ubuntu

      # 3. Install Heavy Dependencies (Only runs if formatting passes)
      - name: Install Build Dependencies (Linux)
        run: |
           sudo apt-get install -y libwayland-dev libgl1-mesa-dev libxkbcommon-dev xorg-dev xvfb doxygen graphviz

      # 3. Configure Cmake, Build Engine, Run Tests and Generate Docs
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Engine
        run: cmake --build build --config Release

      - name: Run Unit Tests
        run: |
          xvfb-run ctest --test-dir build --output-on-failure
          
      - name: Generate Documentation
        run: |
           cmake --build build --target docs
           
      # Upload docs as an artifact so we can download and view them
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: HTML-Docs
          path: docs/api
